# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "master" ]
    tags: 
    - 'v*'
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: test1
      run: |
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
        echo ${{ github.ref_type }}

  test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: test4
      run: echo true
